homepage:
  path: /
  controller: Controller\HomeController::display
display:
  path: /display
  controller: Controller\HomeController::display
login:
  path: /login
  controller: Controller\AuthController::login
logout:
  path: /logout
  controller: Controller\AuthController::logout
register:
path: /register 
  controller: Controller\AuthController::register
create:
  path: /new
  controller: Controller\ContentController::create